// Multiplayer By Caleb

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "AN_SendTargetGroup.generated.h"

/**
 * 
 */
UCLASS()
class CRUNCH_API UAN_SendTargetGroup : public UAnimNotify
{
	GENERATED_BODY()

public:
	virtual void Notify(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Animation,
	                    const FAnimNotifyEventReference& EventReference) override;
private:
	UPROPERTY(EditAnywhere, Category="Ability")
	FGameplayTag EventTag;
	UPROPERTY(EditAnywhere, Category="Ability")
	TArray<FName> TargetSocketNames;
};
